### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by ghost** [spry-group/python-vultr#31] opened 2016-02-21 19:35 UTC
Hi,

I've tried the example on the page along with the sample base_list.py. Neither works for me. Python 2.7 or 3.4 on FreeBSD.

```
2016-02-21 19:33:37,906 INFO [main():77] Vultr API Client Python Library
2016-02-21 19:33:37,907 INFO [main():78] URL: https://www.vultr.com/api/
Traceback (most recent call last):
  File "basic_list.py", line 81, in <module>
    main()
  File "basic_list.py", line 79, in main
    dump_info()
  File "basic_list.py", line 25, in dump_info
    vultr.account.info(), indent=2
AttributeError: 'Vultr' object has no attribute 'account'
```

Basically the same error on both. I'm setting my API key as an environment variable and it should be passed properly.

Is the example out of date or am I doing something wrong?

Thank you,
Teran

**Comment by dopry** [comment] 2016-02-23 17:43
Can you post a gist with the code that isn't working?

**Comment by ghost** [comment] 2016-02-25 05:42
Hi,

I can reproduce it with the basic_list.py example:

```
#$ pwd
/tmp/python-vultr/examples
 #$ echo $VULTR_KEY 
.....(same key works with vultr go client)
 #$ python basic_list.py 
2016-02-25 05:40:58,441 INFO [main():77] Vultr API Client Python Library
2016-02-25 05:40:58,441 INFO [main():78] URL: https://www.vultr.com/api/
Traceback (most recent call last):
  File "basic_list.py", line 81, in <module>
    main()
  File "basic_list.py", line 79, in main
    dump_info()
  File "basic_list.py", line 25, in dump_info
    vultr.account.info(), indent=2
AttributeError: 'Vultr' object has no attribute 'account'
```

Thanks for your reply!

Sincerely,
Teran

**Comment by dopry** [comment] 2016-02-25 14:58
Which version of python-vultr do you have installed? It sounds like you're using the version from pip, 0.1.2, with examples from the master branch, which is latest dev and hasn't been released to pip yet.

**Comment by nishiokay** [comment] 2016-08-23 15:26
Hi,

I have trying to reproduce this issue, but I can't reproduce.

```
# uname -a
FreeBSD freebsd 10.3-RELEASE-p7 FreeBSD 10.3-RELEASE-p7 #0: Thu Aug 11 18:38:15 UTC 2016     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
# python2 basic_list.py
2016-08-23 15:20:17,614 INFO [main():77] Vultr API Client Python Library
2016-08-23 15:20:17,615 INFO [main():78] URL: https://www.vultr.com/api/
2016-08-23 15:20:18,797 INFO [dump_info():25] Listing account info:
{
  "last_payment_amount": "-20.00",
  "balance": "-30",
  "pending_charges": "0.21",
  "last_payment_date": "2016-08-22 11:13:29"
  ... snip ...
```

I have used master branch.
Therefore, I think master branch doesn't have this issue.

Thank you.

**Comment by dopry** [comment] 2016-09-22 05:23
@nishiokay @teran-mckinney I'm closing since it couldn't be re-produced on master. @teran-mckinney if you can reproduce on master let me know and re-open. 

Thanks for your help.

**Closed as completed by dopry** 2016-09-22 05:23 UTC
